# See: https://dart.dev/tools/pub/pubspec
---
name: known_countries
version: 0.0.2
description: >-
  Well-known countries.
homepage: https://github.com/it-is-known
repository: https://github.com/it-is-known/known-countries
issue_tracker: https://github.com/it-is-known/known-countries/issues
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
environment:
  sdk: ^3.11.0
